global:
  sendAnonymousUsage: false

api:
  # insecure: true
  dashboard: true
  debug: false

log:
  # level: DEBUG
  level: ERROR

accessLog: {}

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: vinastic_network
  file:
    filename: /etc/traefik/dynamic_conf/globals.yml

entryPoints:
  http:
    address: ':80'
  https:
    address: ':443'
  mysql:
    address: ':3306/tcp'

certificatesResolvers:
  letsencrypt:
    acme:
      email: contact@tchartron.app
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: http

